### ISSUE TITLE
Hosting on virtualization host.

### ISSUE THREAD

**Issue by Saentist** [solectrus/hosting#15]
Is it possible to be made some appliance for VMWARE PROXMOX hosting service.
Some native installed without docker, if possible.
For example https://www.turnkeylinux.org or even https://www.alpinelinux.org
It will be more easy for migration.

**Comment by ledermann** [comment]
@Saentist Thank you for the suggestion. However, I am not currently planning to provide SOLECTRUS as an appliance for a virtualization platform. I prefer the application deployed as a Docker image, mainly because that's what I have the most experience with.

Nevertheless, if you or someone else is interested in building such an appliance, I would be happy to receive a PullRequest for this.

Thank you for your interest in SOLECTRUS - you are the first user from Bulgaria that I know of :-)

**Comment by Saentist** [comment]
My point of view is opposite, 
Docker pseudo virtualisation is very hard to be used and debugged, 
need extra application layer, and lot of storage.
For me is very hard to understand is `InfluxDB` working or not, 
![image](https://user-images.githubusercontent.com/16975883/218728510-f937e6fe-8daa-4a2d-a986-ff48ea0ba05f.png)
and why `Forecast collector` cannot connect.


----
Standard installed Alpine Linux is less then 64mb when just docker is installed + 1Gb.
Useless blob from my pov.

**Comment by ledermann** [comment]
Too bad that you have trouble with Docker. Yes, if you only need to install Docker for one application, it's a bit overkill. Docker shows its strength when numerous services/apps are to be hosted.

BTW: The Docker image for SOLECTRUS is based on Alpine Linux and is therefore quite lightweight.

For debugging, you can use `docker logs`. 

SOLECTRUS requires some storage services (InfluxDB, PostgresDB, Redis). The hosting guide recommends to use Docker for these services, too, but this is not mandatory - you can connect to external or native services as well. Just change the host names and credentials in your .env file.

I don't know where the screenshot with the 404 error is coming from. Tell me what exactly you have tried and I will try to help you.
